# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_processor.proto\"\xca\x01\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\noperations\x18\x02 \x03(\t\x12\x16\n\x0erotate_degrees\x18\x03 \x01(\x05\x12\x14\n\x0cresize_width\x18\x04 \x01(\x05\x12\x15\n\rresize_height\x18\x05 \x01(\x05\x12\x1a\n\x12generate_thumbnail\x18\x06 \x01(\x08\x12\x17\n\x0fthumbnail_width\x18\x07 \x01(\x05\x12\x18\n\x10thumbnail_height\x18\x08 \x01(\x05\"o\n\rImageResponse\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\x12\x17\n\x0fthumbnail_image\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1b\n\x13intermediate_images\x18\x04 \x03(\x0c\x32?\n\x0eImageProcessor\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=228
  _globals['_IMAGERESPONSE']._serialized_start=230
  _globals['_IMAGERESPONSE']._serialized_end=341
  _globals['_IMAGEPROCESSOR']._serialized_start=343
  _globals['_IMAGEPROCESSOR']._serialized_end=406
# @@protoc_insertion_point(module_scope)
